//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuditTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public long Id { get; set; }
        public System.DateTime Created { get; set; }
        public string EntityFullName { get; set; }
        public string Entity { get; set; }
        public string EntityId { get; set; }
        public string User { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string PropertyName { get; set; }
        public string LogOperation { get; set; }
        public byte[] Signature { get; set; }
        public Nullable<bool> Isvalid { get; set; }
    }
}
