//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuditTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public int com_id { get; set; }
        public string com_code { get; set; }
        public string com_name { get; set; }
        public string com_address { get; set; }
        public string com_zipcode { get; set; }
        public string com_city { get; set; }
        public string com_phonenumber { get; set; }
    }
}
